<script setup>
import { computed,onMounted,onUnmounted,reactive,ref,toRaw } from 'vue'
import { api } from './api.js'
defineProps({loginEnabled:Boolean});defineEmits(['logout'])
import webPackage from '../package.json'
import EventList from './components/EventList.vue';import ProviderCard from './components/ProviderCard.vue';import MonitorDialog from './components/MonitorDialog.vue';import SettingsPage from './components/SettingsPage.vue'
const state=reactive({route:location.hash.slice(1)||'overview',dashboard:{stats:{providers:0,monitoredProviders:0,monitoredPlans:0,inStock:0},providers:[],monitors:[],events:[],runtime:{},version:webPackage.version},events:[],settings:null,update:null});const toast=ref(''),toastError=ref(false);const dialog=reactive({open:false,type:'',providerId:null,provider:null,monitor:null,plans:[],categoryId:null,loading:false,error:'',revision:0})
const now=ref(Date.now());let refreshTimer;const workerOnline=computed(()=>{const tick=Date.parse(state.dashboard.runtime?.lastTickAt);return Number.isFinite(tick)&&now.value-tick<30000});
const titles={overview:['概览','实时状态'],monitors:['监控','监控任务'],providers:['商家','商家与监控'],events:['事件','补货事件'],settings:['设置','设置']};const title=computed(()=>titles[state.route]||titles.overview)
function tip(msg,error=false){toast.value=msg;toastError.value=error;clearTimeout(tip.t);tip.t=setTimeout(()=>toast.value='',2400)}
function clock(v){if(!v)return '尚未运行';return new Date(v).toLocaleString('zh-CN',{hour12:false})}
async function refresh(options={}){now.value=Date.now();state.dashboard=await api('/api/dashboard');if(state.route==='events')state.events=await api('/api/events');if(state.route==='settings'&&options.settings!==false)await loadSettings()}
async function loadSettings(){state.settings=await api('/api/settings');await checkUpdate()}
async function checkUpdate(){state.update=await api('/api/updates/status')}
function onHash(){state.route=location.hash.slice(1)||'overview';if(state.route==='settings')loadSettings().catch(e=>tip(e.message,true));if(state.route==='events')api('/api/events').then(events=>state.events=events).catch(e=>tip(e.message,true))}
let planRequest=0
async function openMonitor(providerId=null,monitor=null){
 const active=monitor?.providerId||providerId,existing=monitor||state.dashboard.monitors.find(m=>m.providerId===active)||null;
 const request=++planRequest;
 Object.assign(dialog,{type:'monitor',categoryId:null,providerId:active,provider:state.dashboard.providers.find(p=>p.id===active)||null,monitor:existing?structuredClone(toRaw(existing)):null,plans:[],loading:!!active,error:'',open:true,revision:dialog.revision+1});
 if(!active)return;
 try{const plans=await api(`/api/providers/${active}/plans`);if(request===planRequest&&dialog.open)dialog.plans=plans}catch(e){if(request===planRequest&&dialog.open)dialog.error=e.message}finally{if(request===planRequest)dialog.loading=false}
}
async function openPlans(provider,categoryId=null){const request=++planRequest;Object.assign(dialog,{categoryId,type:'plans',providerId:provider.id,provider,monitor:null,plans:[],loading:true,error:'',open:true,revision:dialog.revision+1});try{const plans=await api(`/api/providers/${provider.id}/plans`);if(request===planRequest&&dialog.open)dialog.plans=plans}catch(e){if(request===planRequest&&dialog.open)dialog.error=e.message}finally{if(request===planRequest)dialog.loading=false}}
async function saveMonitor(payload){try{await api(dialog.monitor?.id?`/api/monitors/${dialog.monitor.id}`:'/api/monitors',{method:dialog.monitor?.id?'PATCH':'POST',body:JSON.stringify(payload)});dialog.open=false;await refresh();tip('监控任务已保存')}catch(e){tip(e.message,true)}}
async function runMonitor(id){try{await api(`/api/monitors/${id}/run`,{method:'POST',body:'{}'});await refresh();tip('已完成一次探测')}catch(e){await refresh();tip(e.message,true)}}
async function removeMonitor(id){if(!confirm('删除此监控任务？'))return;try{await api(`/api/monitors/${id}`,{method:'DELETE'});await refresh();tip('监控任务已删除')}catch(e){tip(e.message,true)}}
async function saveTelegram(x){try{await api('/api/settings',{method:'PUT',body:JSON.stringify({telegram:x})});await loadSettings();tip('Telegram 设置已保存')}catch(e){tip(e.message,true)}}
async function testTelegram(){try{await api('/api/telegram/test',{method:'POST',body:'{}'});tip('测试消息已发送')}catch(e){tip(e.message,true)}}
async function saveUpdates(x){try{await api('/api/settings',{method:'PUT',body:JSON.stringify({updates:x})});await loadSettings();tip('更新来源已保存')}catch(e){tip(e.message,true)}}
async function applyUpdate(){if(!confirm('将从 GitHub 拉取更新，服务会自动重启。继续吗？'))return;try{const r=await api('/api/updates/apply',{method:'POST',body:'{}'});tip(r.message)}catch(e){tip(e.message,true)}}
onMounted(()=>{window.addEventListener('hashchange',onHash);refresh().catch(e=>tip(e.message,true));refreshTimer=setInterval(()=>refresh({settings:false}).catch(()=>{}),10000)});onUnmounted(()=>{window.removeEventListener('hashchange',onHash);clearInterval(refreshTimer);clearTimeout(tip.t)})
</script>
<template><div class="app-shell"><aside class="sidebar"><a class="brand" href="#overview"><span class="brand-mark">V</span><span>VPS Monitor</span></a><div class="runtime" :class="{ready:workerOnline}"><i></i><span>{{workerOnline?'监控服务运行中':state.dashboard.runtime?.lastTickAt?'监控服务已离线':'监控服务待配置'}}</span></div><nav><a v-for="x in [['overview','概览'],['monitors','监控'],['providers','商家'],['events','补货事件'],['settings','通知设置']]" :key="x[0]" :href="`#${x[0]}`" class="nav-link" :class="{active:state.route===x[0]}">{{x[1]}}</a></nav><div class="sidebar-foot">个人实例<br><span>v{{state.dashboard.version||webPackage.version}}</span></div></aside>
<main><header class="topbar"><div><p class="eyebrow">{{title[0]}}</p><h1>{{title[1]}}</h1></div><div class="button-pair"><button class="button secondary" @click="refresh">立即刷新</button><button v-if="loginEnabled" class="button ghost" @click="$emit('logout')">退出登录</button></div></header><section id="view">
<template v-if="state.route==='overview'"><section class="stats"><article class="stat"><p>已接入商家</p><strong>{{state.dashboard.stats.providers}}</strong></article><article class="stat"><p>已启用监控</p><strong>{{state.dashboard.stats.monitoredProviders}}</strong></article><article class="stat"><p>监控套餐</p><strong>{{state.dashboard.stats.monitoredPlans}}</strong></article><article class="stat"><p>当前有货</p><strong>{{state.dashboard.stats.inStock}}</strong><p v-if="state.dashboard.stats.orderable" class="hint">另有 {{state.dashboard.stats.orderable}} 个可订购，库存未公开</p></article></section><div class="section-head"><div><h2>商家状态</h2><p>仅展示已经发布并可运行的商家 Adapter。</p></div><a class="button secondary" href="#providers">管理商家</a></div><section v-if="state.dashboard.providers.length" class="provider-grid"><ProviderCard v-for="p in state.dashboard.providers" :key="p.id" :provider="p" :monitors="state.dashboard.monitors" @monitor="openMonitor(p.id,state.dashboard.monitors.find(m=>m.providerId===p.id))" @plans="openPlans(p,$event)"/></section><div v-else class="empty">还没有已接入商家。商家 Adapter 发布后会自动显示在这里。</div><div class="section-head"><div><h2>最近事件</h2><p>新上架、补货、售罄和库存变化都会记录在这里</p></div></div><EventList :events="state.dashboard.events" :clock="clock"/></template>
<template v-else-if="state.route==='providers'"><div class="section-head"><div><h2>已接入商家</h2><p>每张卡片对应一个已经发布、可自动抓取全量套餐的 Adapter。</p></div></div><section v-if="state.dashboard.providers.length" class="provider-grid"><ProviderCard v-for="p in state.dashboard.providers" :key="p.id" :provider="p" :monitors="state.dashboard.monitors" @monitor="openMonitor(p.id,state.dashboard.monitors.find(m=>m.providerId===p.id))" @plans="openPlans(p,$event)"/></section><div v-else class="empty">暂无已接入商家。新增商家需要开发 Adapter 并随版本发布。</div></template>
<template v-else-if="state.route==='monitors'"><div class="section-head"><div><h2>监控任务</h2><p>每个已接入商家建立一个任务，可选择全店或部分套餐。</p></div><button class="button" @click="openMonitor()">添加监控</button></div><section v-if="state.dashboard.monitors.length" class="monitor-grid"><article v-for="m in state.dashboard.monitors" :key="m.id" class="panel monitor-card"><div class="provider-top"><div><h3><span class="signal" :class="{off:!m.enabled}"></span> {{m.providerName}}</h3><p class="meta">{{m.scope==='all'?'全部套餐':m.scope==='categories'?'已选分类':'已选套餐'}} · {{m.planCount}} 个套餐 · 每 {{m.intervalSeconds}} 秒</p></div><span class="badge">{{m.enabled?'运行中':'已暂停'}}</span></div><details v-if="m.categories?.length>6" class="monitor-category-summary"><summary>{{m.categories.length}} 个分类 · 查看各分类状态</summary><div class="monitor-categories"><span v-for="category in m.categories" :key="category.id" class="badge">{{category.name}} · {{category.planCount}} 个套餐<span v-if="category.lastError"> · 探测异常</span></span></div></details><div v-else-if="m.categories?.length" class="monitor-categories"><span v-for="category in m.categories" :key="category.id" class="badge">{{category.name}} · {{category.planCount}} 个套餐<span v-if="category.lastError"> · 探测异常</span></span></div><p class="meta">{{m.lastError?`最近失败：${m.lastError}`:`最后检测：${clock(m.lastRunAt)}${m.lastDurationMs?` · ${m.lastDurationMs} ms`:''}`}}</p><div class="card-actions"><span class="meta">连续失败：{{m.consecutiveFailures||0}}</span><div class="button-pair"><button class="button ghost" @click="runMonitor(m.id)">立即运行</button><button class="button secondary" @click="openMonitor(null,m)">编辑</button><button class="button ghost" @click="removeMonitor(m.id)">删除</button></div></div></article></section><div v-else class="empty">还没有监控任务。添加任务后，系统会按设定间隔运行对应商家的 Adapter。</div></template>
<template v-else-if="state.route==='events'"><div class="section-head"><div><h2>套餐上架与库存动态</h2><p>通知模式与北京时间免打扰区间可在通知设置中调整。</p></div></div><EventList :events="state.events" :clock="clock"/></template>
<SettingsPage v-else-if="state.route==='settings'&&state.settings" :settings="state.settings" :update="state.update" @save-telegram="saveTelegram" @test-telegram="testTelegram" @save-updates="saveUpdates" @check-update="checkUpdate" @apply-update="applyUpdate"/>
</section></main><MonitorDialog v-if="dialog.open" :key="dialog.revision" :dialog="dialog" :providers="state.dashboard.providers" :monitors="state.dashboard.monitors" @close="dialog.open=false" @save="saveMonitor" @change-provider="openMonitor($event,null)"/><div class="toast" :class="{show:toast,error:toastError}">{{toast}}</div></div></template>
