<script setup>
import { ref } from 'vue'
import { api } from '../api.js'
import webPackage from '../../package.json'
const props=defineProps({username:String}),emit=defineEmits(['authenticated'])
const username=ref(props.username||'admin'),password=ref(''),showPassword=ref(false),busy=ref(false),error=ref('')
async function login(){if(busy.value)return;busy.value=true;error.value='';try{await api('/api/auth/login',{method:'POST',body:JSON.stringify({username:username.value,password:password.value})});password.value='';emit('authenticated')}catch(e){error.value=e.message}finally{busy.value=false}}
</script>
<template><main class="login-page"><section class="login-story"><a class="brand login-brand" href="#"><span class="brand-mark">V</span><span>VPS Monitor</span></a><div class="login-story-copy"><p class="eyebrow">YOUR PRIVATE MONITOR</p><h1>关注库存变化，<br>把时间留给自己。</h1><p>一个入口，查看商家套餐、管理监控任务，<br class="desktop-break">让每次补货都有迹可循。</p><div class="login-visual" aria-hidden="true"><div class="login-chart"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="login-visual-label"><span class="login-dot"></span>持续探测 · 实时记录</div></div></div><p class="login-story-foot">独立部署 · 你的监控控制台</p></section><section class="login-form-side"><form class="login-form" @submit.prevent="login"><span class="login-tag">实例登录</span><h2>欢迎回来</h2><p class="login-intro">登录后查看库存与监控状态。</p><div class="field"><label for="login-username">用户名</label><input id="login-username" v-model="username" autocomplete="username" required :disabled="busy" placeholder="请输入用户名"></div><div class="field"><label for="login-password">密码</label><div class="login-password"><input id="login-password" v-model="password" :type="showPassword?'text':'password'" autocomplete="current-password" required :disabled="busy" placeholder="请输入密码"><button type="button" :aria-label="showPassword?'隐藏密码':'显示密码'" @click="showPassword=!showPassword">{{showPassword?'隐藏':'显示'}}</button></div></div><p v-if="error" class="login-error" role="alert">{{error}}</p><button class="button login-submit" type="submit" :disabled="busy">{{busy?'正在登录…':'登录控制台'}}<span aria-hidden="true">→</span></button><p class="login-help">使用此实例配置的用户名和密码登录。</p></form><footer class="login-footer">VPS Monitor <span>v{{webPackage.version}}</span></footer></section></main></template>
