<script setup>
import { reactive, watch } from 'vue'
const props=defineProps({dialog:Object,providers:Array,monitors:Array});const emit=defineEmits(['close','save','change-provider'])
const form=reactive({providerId:props.dialog.providerId,enabled:props.dialog.monitor?.enabled!==false,scope:props.dialog.monitor?.scope||'all',planIds:[...(props.dialog.monitor?.planIds||[])],intervalSeconds:props.dialog.monitor?.intervalSeconds||60})
watch(()=>props.dialog.providerId,v=>{form.providerId=v;form.planIds=[]})
function submit(){emit('save',{providerId:form.providerId,enabled:form.enabled,scope:form.scope,planIds:form.planIds,intervalSeconds:form.intervalSeconds})}
</script>
<template><div class="dialog-backdrop" @click.self="$emit('close')"><section class="dialog-card"><button class="close" @click="$emit('close')">×</button>
<template v-if="dialog.type==='plans'"><h2>{{dialog.provider?.name}} 全部套餐</h2><p class="hint">最近一次全量探测结果。</p><section v-if="dialog.plans.length" class="plan-grid modal-plans"><article v-for="p in dialog.plans" :key="p.id" class="plan-card"><p class="meta">{{p.location||'未标注地区'}}</p><h3>{{p.name}}</h3><p class="meta">{{p.specs}}</p><p class="price">{{p.price||'价格未知'}}</p><p class="status" :class="{available:p.available}">{{p.available?'有货':'缺货'}}</p></article></section><div v-else class="empty">尚未抓取到套餐。该 Adapter 下一次成功探测后会自动填充。</div><div class="controls modal-actions"><button class="button ghost" @click="$emit('close')">关闭</button></div></template>
<template v-else><h2>{{dialog.monitor?'编辑':'添加'}}监控任务</h2><p class="hint">同一商家只能有一个任务，避免同一套餐重复通知。</p><div class="field"><label>商家</label><select v-model="form.providerId" :disabled="!!dialog.monitor" @change="$emit('change-provider',form.providerId)"><option v-for="p in providers.filter(p=>!monitors.some(m=>m.providerId===p.id)||p.id===dialog.monitor?.providerId)" :key="p.id" :value="p.id">{{p.name}}</option></select></div><label class="check"><input type="checkbox" v-model="form.enabled"> 启用监控</label><label class="scope-option"><input type="radio" value="all" v-model="form.scope"><span><b>监控全部套餐</b><br>此后自动发现的新套餐也会纳入。</span></label><label class="scope-option"><input type="radio" value="selected" v-model="form.scope"><span><b>只监控以下套餐</b><br>仅勾选套餐触发补货通知。</span></label><div class="monitor-plans"><label v-for="p in dialog.plans" :key="p.id" class="check"><input type="checkbox" :value="p.id" v-model="form.planIds"> {{p.name}} <span class="meta">{{p.location}}</span></label><p v-if="!dialog.plans.length" class="hint">该 Adapter 还没有探测到套餐；先保存“全部套餐”监控，成功抓取后再回来选择。</p></div><div class="field"><label>轮询间隔（秒）</label><input type="number" min="30" max="3600" v-model.number="form.intervalSeconds"></div><div class="controls"><button class="button" @click="submit">保存任务</button><button class="button ghost" @click="$emit('close')">取消</button></div></template>
</section></div></template>
