<script setup>
import { ref,onMounted } from 'vue'
import { startRegistration,browserSupportsWebAuthn } from '@simplewebauthn/browser'
import { api } from '../api.js'
const keys=ref([]),name=ref('我的设备'),password=ref(''),busy=ref(false),message=ref(''),supported=ref(false)
const secure=location.protocol==='https:'&&window.isSecureContext&&browserSupportsWebAuthn()
async function reload(){const config=await api('/api/auth/session');supported.value=secure&&config.passkeySupported;if(supported.value)keys.value=await api('/api/auth/passkeys')}
defineExpose({refresh:reload})
onMounted(()=>reload().catch(e=>message.value=e.message))
async function act(fn){if(busy.value)return;busy.value=true;message.value='';try{await fn();password.value='';await reload();message.value='Passkey 设置已保存'}catch(e){message.value=e.name==='NotAllowedError'?'操作已取消或设备验证超时':e.message}finally{busy.value=false}}
async function add(){await act(async()=>{const request=await api('/api/auth/passkeys/register/options',{method:'POST',body:JSON.stringify({currentPassword:password.value})});const response=await startRegistration({optionsJSON:request.options});await api('/api/auth/passkeys/register/verify',{method:'POST',body:JSON.stringify({requestId:request.requestId,response,name:name.value})})})}
async function remove(key){if(!confirm(`删除「${key.name}」？其他设备的登录会话也会退出。`))return;await act(()=>api('/api/auth/passkeys',{method:'DELETE',body:JSON.stringify({id:key.id,currentPassword:password.value})}))}
async function rename(key){const value=prompt('新的 Passkey 名称',key.name);if(!value)return;await act(()=>api('/api/auth/passkeys',{method:'PATCH',body:JSON.stringify({id:key.id,name:value,currentPassword:password.value})}))}
</script>
<template><section class="setting-grid update-section"><form class="panel settings-card" @submit.prevent="add"><h2>Passkey 登录</h2><p>使用设备的指纹、面容或 PIN 登录；保留密码作为恢复方式。</p><p v-if="!supported" class="hint">请通过 HTTPS 域名访问，并使用支持 Passkey 的浏览器。实例需先配置登录密码。</p><template v-else><div class="field"><label for="passkey-password">当前密码（添加、重命名或删除时验证）</label><input id="passkey-password" v-model="password" type="password" autocomplete="current-password" required :disabled="busy"></div><div class="field"><label for="passkey-name">新 Passkey 名称</label><input id="passkey-name" v-model="name" maxlength="80" required :disabled="busy"></div><button class="button" :disabled="busy">{{busy?'正在处理…':'添加 Passkey'}}</button><p v-if="!keys.length">尚未添加 Passkey。</p><div v-for="key in keys" :key="key.id" class="passkey-row"><strong>{{key.name}}</strong><p class="hint">添加：{{new Date(key.createdAt).toLocaleString()}} · 最近使用：{{key.lastUsedAt?new Date(key.lastUsedAt).toLocaleString():'尚未使用'}}</p><div class="controls"><button type="button" class="button secondary" :disabled="busy||!password" @click="rename(key)">重命名</button><button type="button" class="button secondary" :disabled="busy||!password" @click="remove(key)">删除</button></div></div></template><p v-if="message" role="status">{{message}}</p></form></section></template>
