<script setup>
import {ref,computed,onMounted,onUnmounted} from 'vue'
import {planLocation} from '../plan-location.js'
import {api} from '../api.js'
import PublicPlanCard from './PublicPlanCard.vue'
import {groupPlans} from '../plan-groups.js'
defineProps({authenticated:Boolean})
const data=ref({providers:[],plans:[],events:[]}),error=ref(''),loading=ref(true),route=ref(location.hash.slice(1)||'home')
const section=computed(()=>route.value.split('/')[0]),providerId=computed(()=>decodeURIComponent(route.value.split('/')[1]||'')),provider=computed(()=>data.value.providers.find(p=>p.id===providerId.value))
const activeMerchant=computed(()=>providerId.value||'all')
const groupPages=ref({})
const merchantGroups=computed(()=>data.value.providers.filter(p=>activeMerchant.value==='all'||p.id===activeMerchant.value).map(p=>{
 const merchantPlans=data.value.plans.filter(plan=>plan.providerId===p.id)
 return {...p,planCount:merchantPlans.length,groups:groupPlans(merchantPlans,(p.categories||[]).filter(c=>!c.retired)).map(group=>{
  const key=`${p.id}:${group.id}`,pages=Math.max(1,Math.ceil(group.plans.length/24)),page=Math.min(groupPages.value[key]||1,pages)
  return {...group,key,page,pages,visible:group.plans.slice((page-1)*24,page*24)}
 })}
}))
const plans=computed(()=>activeMerchant.value==='all'?data.value.plans:data.value.plans.filter(p=>p.providerId===activeMerchant.value))
function selectMerchant(id){location.hash=id==='all'?'plans':`plans/${encodeURIComponent(id)}`}
function changePage(group,delta){groupPages.value[group.key]=group.page+delta}
const names=computed(()=>Object.fromEntries(data.value.providers.map(p=>[p.id,p.name])))
const labels={new_plan:'新上架',restocked:'补货',sold_out:'售罄',stock_changed:'库存变化',delisted:'下架'}
const clock=value=>new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value))
const stock=p=>!p.available?'已售罄':Number.isInteger(p.quantity)?`有货 · ${p.quantity} 台`:'可订购 · 数量未公开'
async function load(){try{data.value=await api('/api/public/catalog');error.value=''}catch(e){error.value=e.message}finally{loading.value=false}}
function navigate(){route.value=location.hash.slice(1)||'home';groupPages.value={};window.scrollTo(0,0)}
let timer
onMounted(()=>{load();timer=setInterval(load,30000);window.addEventListener('hashchange',navigate)})
onUnmounted(()=>{clearInterval(timer);window.removeEventListener('hashchange',navigate)})
</script>
<template><div class="public-site"><header class="public-header"><div class="public-nav"><a href="/#home" class="public-brand"><span>V</span> VPS Monitor</a><nav aria-label="展示页导航"><a v-for="item in [['home','首页'],['merchants','商家'],['plans','套餐'],['activity','动态']]" :href="`/#${item[0]}`" :class="{active:section===item[0]}">{{item[1]}}</a></nav><a href="/admin" class="public-login">{{authenticated?'后台':'登录'}} ↗</a></div></header><main class="public-main"><p v-if="error" role="alert" class="public-error">{{error}} <button @click="load">重试</button></p><p v-if="loading" class="public-empty">正在加载库存…</p><template v-else>
<template v-if="section==='home'"><section class="public-hero"><p class="public-eyebrow">VPS 库存观察站</p><h1>好机器，<span>及时发现。</span></h1><p>关注商家库存与新套餐，让每一次上架和补货都有迹可循。</p><div class="public-actions"><a href="/#plans" class="public-primary">浏览全部套餐 →</a><a href="/#activity">查看最新动态 ↗</a></div><div class="public-stats"><div><strong>{{data.providers.length}}</strong><span>已接入商家</span></div><div><strong>{{data.plans.length}}</strong><span>当前套餐</span></div><div><strong>{{data.plans.filter(p=>p.available).length}}</strong><span>有货 / 可订购</span></div></div><aside class="public-live-feed"><div class="public-feed-title"><span>◉ 实时库存动态</span><small>SIGNAL FEED</small></div><article v-for="e in data.events.slice(0,3)" :key="e.id"><span class="public-feed-dot" :class="e.type"></span><div><strong>{{e.message}}</strong><small>{{names[e.providerId]}} · {{clock(e.at)}}</small></div></article><p v-if="!data.events.length" class="public-feed-empty">持续关注库存<br><small>套餐变化后自动显示动态</small></p><div class="public-feed-foot">每 30 秒刷新 <span>● 公开库存数据</span></div></aside></section><div class="public-section-title"><div><p class="public-eyebrow">MERCHANTS</p><h2>商家一览</h2></div><a href="/#merchants">全部商家 →</a></div></template>
<template v-if="section==='home'||section==='merchants'&&!providerId"><div v-if="section==='merchants'" class="public-page-title"><h1>商家</h1><p>已接入的全部商家与当前套餐库存。</p></div><div class="public-merchants"><a v-for="p in data.providers" :key="p.id" :href="`/#merchants/${encodeURIComponent(p.id)}`" class="public-merchant"><div class="public-merchant-icon">{{p.name.slice(0,1)}}</div><h3>{{p.name}}</h3><p>{{data.plans.filter(x=>x.providerId===p.id).length}} 个套餐 <span>· {{data.plans.filter(x=>x.providerId===p.id&&x.available).length}} 个有货 / 可订购</span></p><footer>查看商家套餐 <span>↗</span></footer></a></div><p v-if="!data.providers.length" class="public-empty">暂未接入商家</p></template>
<template v-if="section==='plans'||section==='merchants'&&providerId"><div class="public-page-title"><a v-if="providerId" href="/#merchants">← 返回商家</a><h1>{{provider?.name||'全部套餐'}}</h1><p>{{plans.length}} 个当前套餐 · 库存来自最近一次成功采集</p><a v-if="provider?.website" :href="provider.website" target="_blank" rel="noopener noreferrer">访问商家官网 ↗</a></div><div class="public-merchant-tabs" role="tablist" aria-label="套餐商家"><button role="tab" :aria-selected="activeMerchant==='all'" @click="selectMerchant('all')">全部 <span>{{data.plans.length}}</span></button><button v-for="p in data.providers" :key="p.id" role="tab" :aria-selected="activeMerchant===p.id" @click="selectMerchant(p.id)">{{p.name}} <span>{{data.plans.filter(plan=>plan.providerId===p.id).length}}</span></button></div>
<section v-for="merchant in merchantGroups" :key="merchant.id" class="public-merchant-section" :aria-label="`${merchant.name} 套餐`"><header class="public-merchant-heading"><div><h2>{{merchant.name}}</h2><p>{{merchant.planCount}} 个当前套餐 · {{merchant.groups.length}} 个分类</p></div><a v-if="merchant.website" :href="merchant.website" target="_blank" rel="noopener noreferrer">商家官网 ↗</a></header><section v-for="group in merchant.groups" :key="group.key" class="public-category-section" :aria-label="group.name"><header class="public-category-heading"><h3>{{group.name}}</h3><span>{{group.plans.length}} 个套餐</span></header><div class="public-plans"><PublicPlanCard v-for="p in group.visible" :key="p.id" :plan="p" :provider-name="merchant.name"/></div><p v-if="!group.plans.length" class="public-empty">该分类当前没有公开套餐。</p><div v-if="group.pages>1" class="public-pagination"><button :disabled="group.page===1" @click="changePage(group,-1)">上一页</button><span>{{group.page}} / {{group.pages}}</span><button :disabled="group.page===group.pages" @click="changePage(group,1)">下一页</button></div></section><p v-if="!merchant.groups.length" class="public-empty">该商家尚未采集到套餐。</p></section><p v-if="!merchantGroups.length" class="public-empty">尚未采集到套餐，请稍后查看。</p></template>
<template v-if="section==='home'||section==='activity'"><div class="public-section-title"><div><p class="public-eyebrow">LIVE ACTIVITY</p><h2>{{section==='home'?'最新动态':'套餐动态'}}</h2><p>新上架、补货、售罄和库存变化 · 北京时间</p></div><a v-if="section==='home'" href="/#activity">全部动态 →</a></div><section class="public-events"><article v-for="e in (section==='home'?data.events.slice(0,8):data.events)" :key="e.id"><time>{{clock(e.at)}}</time><span class="public-event-type" :class="e.type">{{labels[e.type]}}</span><div><a :href="`/#merchants/${encodeURIComponent(e.providerId||'')}`">{{names[e.providerId]||'商家'}}</a><p>{{e.message}}</p><small v-if="e.snapshot" class="public-event-specs">{{[e.snapshot.price,e.snapshot.specs,planLocation({providerId:e.providerId,location:e.snapshot.location})].filter(Boolean).join(' · ')}}</small></div></article><p v-if="!data.events.length" class="public-empty">暂时没有套餐变化，发现上架或库存变化后会显示在这里。</p></section></template></template></main><footer class="public-footer"><span>VPS Monitor · v{{data.version}}</span><p>库存和价格以商家购买页为准。展示数据每 30 秒刷新。</p><a href="/admin">管理后台 ↗</a></footer></div></template>
