<script setup>
import { watch, reactive, ref } from 'vue';import { api } from '../api.js'
const props=defineProps({settings:Object,update:Object,updateChecking:Boolean});defineEmits(['save-telegram','test-telegram','save-updates','check-update','apply-update'])
const tg=reactive({botToken:'',chatId:props.settings.telegram.chatId||'',enabled:!!props.settings.telegram.enabled,showBuyLink:props.settings.telegram.showBuyLink!==false,notifyNewPlans:!!props.settings.telegram.notifyNewPlans,notificationMode:props.settings.telegram.notificationMode||'restock',quietHours:{enabled:false,start:'23:00',end:'08:00',...props.settings.telegram.quietHours}});const up=reactive({repository:props.settings.updates.repository||'',branch:props.settings.updates.branch||'main'});const previews=reactive({restock:'正在生成预览...',soldout:'正在生成预览...',stock:'正在生成预览...'})
watch(()=>props.settings.telegram,async(settings,previous,onCleanup)=>{
  let current=true;onCleanup(()=>current=false);
  // Only a successful save or reload replaces this prop; clear the submitted secret then.
  tg.botToken='';tg.chatId=settings.chatId||'';tg.enabled=!!settings.enabled;tg.notifyNewPlans=!!settings.notifyNewPlans;tg.showBuyLink=settings.showBuyLink!==false;tg.notificationMode=settings.notificationMode||'restock';Object.assign(tg.quietHours,{enabled:false,start:'23:00',end:'08:00'},settings.quietHours||{});
  const clean=text=>text.replace(/<[^>]*>/g,'');
  try{const [restock,soldout,stock]=await Promise.all([api('/api/telegram/preview',{method:'POST',body:'{}'}),api('/api/telegram/preview',{method:'POST',body:JSON.stringify({status:'sold_out'})}),api('/api/telegram/preview',{method:'POST',body:JSON.stringify({status:'stock_changed',plan:{previousQuantity:5,quantity:3}})})]);if(current){previews.restock=clean(restock.text);previews.soldout=clean(soldout.text);previews.stock=clean(stock.text);}}catch{if(current){previews.restock='预览加载失败';previews.soldout='预览加载失败';previews.stock='预览加载失败';}}
},{immediate:true})
const passwords=reactive({currentPassword:'',newPassword:'',confirmPassword:''}),passwordBusy=ref(false),passwordMessage=ref(''),passwordError=ref(false)
async function changePassword(){passwordBusy.value=true;passwordMessage.value='';passwordError.value=false;try{await api('/api/auth/password',{method:'POST',body:JSON.stringify(passwords)});Object.assign(passwords,{currentPassword:'',newPassword:'',confirmPassword:''});passwordMessage.value='密码已修改，其他登录会话已退出。'}catch(e){passwordError.value=true;passwordMessage.value=e.message}finally{passwordBusy.value=false}}
</script>
<template><section class="setting-grid"><form class="panel settings-card" @submit.prevent="$emit('save-telegram',{...tg})"><h2>Telegram 频道通知</h2><p>Bot 必须是目标频道管理员，才能发送及编辑补货卡片。</p><div class="field"><label>Bot Token</label><input v-model="tg.botToken" type="password" :placeholder="settings.telegram.botTokenConfigured?'已保存，留空则不修改':'123456:ABC...'"></div><div class="field"><label>频道 Chat ID</label><input v-model="tg.chatId" placeholder="-1001234567890"></div><label class="check"><input type="checkbox" v-model="tg.enabled"> 开启 TG 通知</label><label class="check"><input type="checkbox" v-model="tg.showBuyLink"> 在卡片中展示购买链接</label><label class="check"><input type="checkbox" v-model="tg.notifyNewPlans"> 新套餐上架通知</label><p class="hint">商家首次成功采集建立基线；之后发现新套餐自动解析并推送 TG，包括新分类及售罄的新套餐。此开关覆盖该商家所有新套餐，商家监控须启用；遵守 TG 总开关与免打扰。</p><div class="field"><label for="notification-mode">库存通知模式</label><select id="notification-mode" v-model="tg.notificationMode"><option value="restock">仅补货推送（默认）</option><option value="all">全部库存变化推送</option></select></div><p class="hint">仅补货：补货发新卡片，库存变化和售罄编辑原卡片。全部变化：监控范围内的补货、库存数量变化、售罄都发新卡片；状态不变不重复推送。开启不会批量发送已有套餐。</p><label class="check"><input type="checkbox" v-model="tg.quietHours.enabled"> 开启免打扰（北京时间 UTC+8）</label><div class="quiet-hours-fields"><div class="field"><label for="quiet-start">免打扰开始时间</label><input id="quiet-start" type="time" v-model="tg.quietHours.start" :disabled="!tg.quietHours.enabled" required></div><div class="field"><label for="quiet-end">免打扰结束时间</label><input id="quiet-end" type="time" v-model="tg.quietHours.end" :disabled="!tg.quietHours.enabled" required></div></div><p class="hint">支持跨午夜，例如 23:00–08:00。包含开始时间，不包含结束时间。期间继续监控，暂停 TG 发送与编辑（含测试消息），结束后补发；全部变化模式的卡片保留当时库存和北京时间。</p><div class="controls"><button class="button">保存设置</button><button class="button secondary" type="button" @click="$emit('test-telegram')">测试 TG 连通性</button></div></form><aside class="panel settings-card"><h2>卡片预览</h2><p>库存由商家页面数据决定：有数量即显示，无数量则自动隐藏。</p><p class="preview-label">补货卡片</p><pre class="preview">{{previews.restock}}</pre><p class="preview-label">库存变化卡片（全部变化模式）</p><pre class="preview">{{previews.stock}}</pre><p class="preview-label">售罄卡片</p><pre class="preview">{{previews.soldout}}</pre></aside></section>
<section class="setting-grid update-section"><form class="panel settings-card" @submit.prevent="$emit('save-updates',{...up})"><h2>在线更新</h2><p>源码和安装包部署均支持在线更新。检查新版本后确认更新，完成后服务自动重启并刷新页面。</p><div class="field"><label>GitHub 仓库</label><input v-model="up.repository" placeholder="owner/repository"></div><div class="field"><label>发布分支</label><input v-model="up.branch"></div><button class="button">保存更新来源</button></form><aside class="panel settings-card"><h2>版本状态</h2><p>{{update?.message||'正在检查 GitHub 版本...'}}</p><div class="controls"><button class="button secondary" type="button" :disabled="updateChecking" @click="$emit('check-update')">{{updateChecking?'正在检查…':'检查更新'}}</button><button v-if="update?.updateAvailable&&update?.deployReady" class="button" type="button" @click="$emit('apply-update')">在线更新并重启</button></div><p class="hint" v-if="update?.mode==='release'">当前 v{{update.localVersion}}<span v-if="update.remoteVersion"> · 已发布 v{{update.remoteVersion}}</span></p><a v-if="update?.mode==='release'&&update.releaseUrl" class="button secondary" :href="update.releaseUrl" target="_blank" rel="noopener noreferrer">查看发布包</a><p class="hint" v-if="update?.localRevision">当前 {{update.localRevision.slice(0,8)}} · 远端 {{update.remoteRevision?.slice(0,8)||'未找到'}}</p></aside></section><section class="setting-grid update-section"><form class="panel settings-card" @submit.prevent="changePassword"><h2>修改密码</h2><p>修改后当前会话保持登录，其他设备需要使用新密码重新登录。</p><template v-if="settings.security?.passwordProtected"><div class="field"><label for="current-password">当前密码</label><input id="current-password" v-model="passwords.currentPassword" type="password" autocomplete="current-password" required maxlength="1024"></div><div class="field"><label for="new-password">新密码</label><input id="new-password" v-model="passwords.newPassword" type="password" autocomplete="new-password" required minlength="8" maxlength="128"></div><div class="field"><label for="confirm-password">确认新密码</label><input id="confirm-password" v-model="passwords.confirmPassword" type="password" autocomplete="new-password" required minlength="8" maxlength="128"></div><button class="button" :disabled="passwordBusy">{{passwordBusy?'正在修改…':'修改密码'}}</button><p v-if="passwordMessage" :role="passwordError?'alert':'status'">{{passwordMessage}}</p></template><p v-else>请先通过 ADMIN_PASSWORD 配置初始登录密码。</p></form></section></template>
