<script setup>
import {ref,onMounted,onUnmounted,nextTick} from 'vue'
const props=defineProps({update:Object,status:Object,phase:String,error:String}),emit=defineEmits(['confirm','close','retry'])
const dialog=ref(null),busy=()=>!['confirm','failed'].includes(props.phase)
function key(event){if(event.key==='Escape'&&!busy())emit('close');if(event.key==='Tab'){const nodes=[...dialog.value.querySelectorAll('button:not(:disabled),a[href]')];if(!nodes.length){event.preventDefault();return}const first=nodes[0],last=nodes.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}}
let previous
onMounted(async()=>{previous=document.activeElement;await nextTick();dialog.value.focus();window.addEventListener('keydown',key)})
onUnmounted(()=>{window.removeEventListener('keydown',key);previous?.focus()})
</script>
<template><div class="dialog-backdrop update-backdrop"><section ref="dialog" class="dialog-card update-dialog" role="dialog" aria-modal="true" aria-labelledby="update-title" tabindex="-1"><button v-if="!busy()" type="button" class="close" aria-label="关闭更新弹窗" @click="$emit('close')">×</button><p class="eyebrow">系统更新</p><h2 id="update-title">{{phase==='confirm'?'发现新版本':phase==='failed'?'更新未完成':'正在在线更新'}}</h2><template v-if="phase==='confirm'"><p>当前 v{{update?.localVersion}}<span v-if="update?.remoteVersion"> → v{{update.remoteVersion}}</span><span v-else> → 最新发布分支</span></p><p class="hint">确认后下载并校验更新，备份原部署。更新期间暂停监控，保留数据库、登录和 TG 设置。完成后自动重启服务并刷新此页面。</p><div class="controls modal-actions"><button class="button secondary" type="button" @click="$emit('close')">暂不更新</button><button class="button" type="button" @click="$emit('confirm')">确定更新</button></div></template><template v-else><p v-if="status?.targetVersion">目标版本 v{{status.targetVersion}}</p><div class="update-progress-label"><span>{{phase==='failed'?'更新失败':`${status?.progress||0}%`}}</span><span>{{status?.state==='restarting'?'正在重新连接服务':''}}</span></div><progress class="update-progress" :value="status?.progress||0" max="100" aria-label="在线更新进度"></progress><p class="update-message" :role="phase==='failed'?'alert':'status'" aria-live="polite">{{error||status?.message||'正在准备更新…'}}</p><p v-if="phase!=='failed'" class="hint">无需手动刷新，服务恢复后页面会自动刷新。</p><div v-else class="controls modal-actions"><button type="button" class="button secondary" @click="$emit('close')">关闭</button><button type="button" class="button" @click="$emit('retry')">重新检查</button></div></template></section></div></template>
